// scripts/build-api.mjs
import { build } from "esbuild";
import { fileURLToPath } from "url";
import path from "path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

await build({
  entryPoints: [path.join(root, "src/server/generate-pdf.entry.js")],
  outfile: path.join(root, "api/generate-pdf.js"),
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  external: ["puppeteer-core", "@sparticuz/chromium", "puppeteer"],
  jsx: "automatic",
  banner: {
    js: "// AUTO-GENERATED by scripts/build-api.mjs — DO NOT EDIT DIRECTLY.\n// Edit src/server/generate-pdf.entry.js instead, then run: node scripts/build-api.mjs",
  },
});

console.log("✅ api/generate-pdf.js bundled successfully");